/**
 * useNews Hook
 *
 * Fetches extracted news items from email content and provides
 * actions for saving/dismissing news.
 *
 * NEW (Feb 2026): News extraction from newsletter/news content.
 * News items are generated by the NewsBriefAnalyzer and stored in
 * email_analyses.news_brief. This hook reads them via the News API.
 *
 * @module hooks/useNews
 * @since February 2026
 */

'use client';

import { useState, useEffect, useCallback } from 'react';
import { createLogger } from '@/lib/utils/logger';

const logger = createLogger('useNews');

// ═══════════════════════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * A single news item from email analysis.
 */
export interface NewsItemDisplay {
  /** One-line factual headline */
  headline: string;
  /** One sentence of context/implications */
  detail: string;
  /** Topic tags for filtering and grouping */
  topics: string[];
  /** Specific date mentioned (YYYY-MM-DD), if any */
  dateMentioned: string | null;
  /** Confidence score (0-1) */
  confidence: number;
  /** Source email ID */
  emailId: string;
  /** Source email subject (for context) */
  emailSubject: string | null;
  /** Source email sender name/email */
  emailSender: string | null;
  /** When the email was analyzed (ISO string) */
  analyzedAt: string;
}

/**
 * Topic with count for stats.
 */
export interface TopicCount {
  topic: string;
  count: number;
}

/**
 * Statistics about extracted news.
 */
export interface NewsStats {
  totalNews: number;
  savedNews: number;
  topTopics: TopicCount[];
  avgConfidence: number;
}

/**
 * Options for the hook.
 */
export interface UseNewsOptions {
  /** Number of emails to check for news (default: 10) */
  limit?: number;
  /** Filter by topic tag */
  topic?: string;
  /** Minimum confidence threshold (default: 0.3) */
  minConfidence?: number;
  /** Auto-refresh interval in ms (0 = disabled, default: 0) */
  refreshInterval?: number;
  /** Skip initial fetch */
  skip?: boolean;
}

/**
 * Return type for the hook.
 */
export interface UseNewsReturn {
  /** News items */
  items: NewsItemDisplay[];
  /** Statistics */
  stats: NewsStats | null;
  /** Loading state */
  isLoading: boolean;
  /** Error if any */
  error: Error | null;
  /** Manually refetch news */
  refetch: () => Promise<void>;
  /** Save a news item to the saved_news table */
  saveNews: (item: NewsItemDisplay) => Promise<void>;
  /** Dismiss a news item (remove from list) */
  dismissNews: (item: NewsItemDisplay) => void;
}

// ═══════════════════════════════════════════════════════════════════════════════
// HOOK
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Hook to fetch and manage news items from email analysis.
 *
 * @param options - Configuration options
 * @returns News items with loading/error states and actions
 *
 * @example
 * ```tsx
 * const { items, stats, isLoading, saveNews } = useNews({ limit: 10 });
 *
 * return items.map(item => (
 *   <NewsCard
 *     key={`${item.emailId}-${item.headline.substring(0, 20)}`}
 *     item={item}
 *     onSave={() => saveNews(item)}
 *   />
 * ));
 * ```
 */
export function useNews(options: UseNewsOptions = {}): UseNewsReturn {
  const {
    limit = 10,
    topic,
    minConfidence = 0.3,
    refreshInterval = 0,
    skip = false,
  } = options;

  const [items, setItems] = useState<NewsItemDisplay[]>([]);
  const [stats, setStats] = useState<NewsStats | null>(null);
  const [isLoading, setIsLoading] = useState(!skip);
  const [error, setError] = useState<Error | null>(null);

  /**
   * Fetch news from the API.
   */
  const fetchNews = useCallback(async () => {
    try {
      setIsLoading(true);
      setError(null);

      logger.debug('Fetching news', { limit, topic, minConfidence });

      const params = new URLSearchParams({ limit: String(limit) });
      if (topic) params.set('topic', topic);
      if (minConfidence !== 0.3) params.set('min_confidence', String(minConfidence));

      const response = await fetch(`/api/news?${params.toString()}`);

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Failed to fetch news');
      }

      const result = await response.json();

      setItems(result.items || []);
      setStats(result.stats || null);

      logger.debug('News fetched', {
        newsCount: result.items?.length ?? 0,
        savedCount: result.stats?.savedNews ?? 0,
      });
    } catch (err) {
      const fetchError = err instanceof Error ? err : new Error('Unknown error');
      logger.error('News fetch failed', { error: fetchError.message });
      setError(fetchError);
    } finally {
      setIsLoading(false);
    }
  }, [limit, topic, minConfidence]);

  /**
   * Save a news item to the saved_news table.
   * Removes it from the current list (it's now "saved").
   */
  const saveNews = useCallback(async (item: NewsItemDisplay) => {
    logger.info('Saving news item', {
      emailId: item.emailId.substring(0, 8),
      preview: item.headline.substring(0, 40),
    });

    try {
      const response = await fetch('/api/news', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          headline: item.headline,
          detail: item.detail,
          topics: item.topics,
          dateMentioned: item.dateMentioned,
          confidence: item.confidence,
          emailId: item.emailId,
        }),
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Failed to save news item');
      }

      // Remove from list and update stats
      setItems(prev => prev.filter(n =>
        !(n.emailId === item.emailId && n.headline === item.headline)
      ));
      setStats(prev => prev ? {
        ...prev,
        savedNews: prev.savedNews + 1,
        totalNews: prev.totalNews - 1,
      } : prev);

      logger.success('News item saved', { headline: item.headline.substring(0, 40) });
    } catch (err) {
      logger.error('Save news failed', {
        error: err instanceof Error ? err.message : 'Unknown error',
      });
      throw err;
    }
  }, []);

  /**
   * Dismiss a news item — removes it from the current view.
   * Does NOT persist the dismissal (items regenerate on refresh).
   */
  const dismissNews = useCallback((item: NewsItemDisplay) => {
    logger.debug('Dismissing news item', { headline: item.headline.substring(0, 30) });
    setItems(prev => prev.filter(n =>
      !(n.emailId === item.emailId && n.headline === item.headline)
    ));
  }, []);

  // Initial fetch
  useEffect(() => {
    if (!skip) {
      fetchNews();
    }
  }, [skip, fetchNews]);

  // Auto-refresh interval
  useEffect(() => {
    if (refreshInterval > 0 && !skip) {
      const interval = setInterval(fetchNews, refreshInterval);
      return () => clearInterval(interval);
    }
  }, [refreshInterval, skip, fetchNews]);

  return {
    items,
    stats,
    isLoading,
    error,
    refetch: fetchNews,
    saveNews,
    dismissNews,
  };
}

export default useNews;
